@startuml Portal
actor UL as "Usuario logueado"
actor UNL as "Usuario no logueado"
actor Administrador


usecase CrearPagina as "Crear nueva página
----
Extension point
Previsualizar página"
usecase HExplotacion as "Usar herramienta de \n explotacion de Web
----
Extension point
Publicar contenido
Eliminar contenido
Modificar contenido"

usecase Buscar as "Buscar
----
Extension point
Elegir idioma
Buscar por secciones"

Administrador--|>UL
UL--|>UNL


Administrador--(Editar la Web)
(Editar la Web).>(Emplear editor WYSIWYG) : <<include>>
Administrador--(Modificar diseño de la página)
Administrador--HExplotacion 
(Publicar contenido) ..>HExplotacion : <<extend>>
(Eliminar contenido) ..>HExplotacion : <<extend>>
(Modificar contenido) ..>HExplotacion : <<extend>>
Administrador--(Visualizar estadísticas de \n acceso Vista Administrador) 
(Visualizar estadísticas de \n acceso Vista Administrador)--|>(Visualizar estadísticas \n de acceso)
Administrador--(Usar espacios de trabajo de compartido)


UL--CrearPagina
(Previsualizar página)..>CrearPagina: <<extend>>
UL--(Visualizar estadísticas \n de acceso)


UNL--(Foros)
UNL--(Blogs)
UNL--(Cloud tag)
(Foros)--|>(Utilizar herramientas Web 2.0)
(Blogs)--|>(Utilizar herramientas Web 2.0)
(Cloud tag)--|>(Utilizar herramientas Web 2.0)
UNL--(Buscar)
(Buscar por secciones)..>(Buscar) : <<extends>>
(Elegir idioma)..>(Buscar) : <<extends>>

@enduml