@startuml SIIT
actor UI as "Usuario invitado"
actor UL as "Usuario Logueado"
actor Usuario
actor Subcontratado
actor Administrador
actor Comun

usecase (Modificar) as "Modificar datos"
usecase (Introducir) as "Introduccion manual de datos"


Usuario--|>Comun
Administrador--|>Comun

UI--|>Usuario
UL--|>Usuario

usecase (Ayuda) as  "Obtener ayuda en linea"
usecase (Consulta) as "Realizar Consulta"
usecase Horarios as "Visualizar listado de horarios y lineas
--
extension points
Visualizar Informacion Adicional"
usecase (Potenciar) as "Introducir Parametros a potenciar"
usecase Origen as "Introducir origen y destino
--
extension points
Utilizar mapa
Direccion
Barrio
Detalle Paradas
Evento Cultural"


usecase (Direccion) as "Direccion"
usecase (Barrio) as "Barrio"
usecase (Detalle) as "Detalle Paradas"
usecase (Evento) as "Evento Cultural"
usecase Mapa as "Utilizar Mapa
--
extension points
Acercar
Alejar
Desplazar
Ir a mapa base
Centrar
"

usecase (Acercar) as "Acercar"
usecase (Alejar) as "Alejar"
usecase (Desplazar) as "Desplazar"
usecase (MapaB) as "Ir a mapa base"
usecase (Centrar) as "Centrar"


(Origen)<.up.(Mapa) : <<extends>>
(Origen)<..(Direccion) : <<extends>>
(Origen)<..(Barrio) : <<extends>>
(Origen)<..(Detalle) : <<extends>>
(Origen)<..(Evento) : <<extends>>


(Mapa)<..(Acercar) : <<extends>>
(Mapa)<.up.(Alejar) : <<extends>>
(Mapa)<.left.(Desplazar) : <<extends>>
(Mapa)<.up.(MapaB) : <<extends>>
(Mapa)<..(Centrar) : <<extends>>



Administrador--Modificar
Administrador--Introducir
Comun--Horarios


usecase Parametros as "Introducir Parámetros
--
extension points
Parametros a potenciar
"

Usuario--Consulta
Usuario--Ayuda
Subcontratado--Ayuda

(Consulta)..>(Parametros) : <<include>> 
(Parametros)..>(Origen) : <<include>> 
(Parametros)<.up.(Potenciar) : <<extends>>



usecase Solucion as "Visualizar recorrido solución
--
extension points
Visualizar Informacion Adicional"

usecase MostrarInfo as "Visualizar Informacion Adicional
--
extension points
Parada
Linea"
usecase MostrarInfoConsulta as "Visualizar Informacion Adicional Consulta
--
extensions points
Itinerario"


(Origen)...>(Solucion) : <<include>> 
(Solucion)<..MostrarInfoConsulta : <<extends>>
(Horarios)<.right.(MostrarInfo) : <<extends>>


(MostrarInfoConsulta)-right-|>(MostrarInfo)

(MostrarInfo)<..(Parada) : <<extends>>
(MostrarInfo)<..(Linea) : <<extends>>
(MostrarInfoConsulta)<..(Itinerario) : <<extends>>


@enduml