@startuml Sistema de informacion
actor OA as "Operador adjudicatario"
actor Operador
actor UR as "Usuario logueado"
actor UNR as "Usuario no logueado"
usecase VisualAct as "Visualizar la actividad 
de los operadores 
en la cartografía
--
extension points
Introducir operadores
"
OA-left-VisualAct
(Registrar situaciones puntuales)--OA 
(Registrar periodos continuos)--OA
usecase (Visualizar alarmas UR) as "Visualizar alarmas (UL)"
usecase (Visualizar alarmas OA) as "Visualizar alarmas (OA)"
usecase (Visualizar alarmas O) as "Visualizar alarmas (O)"
usecase VA as "Visualizar alarmas 
--
extension points 
Mostrar mensaje"

usecase DE as "Definir eventos 
--
extension points
Generar avisos"

usecase (Generar avisos) as GA
usecase EX as "Examinar 
la explotación
en tiempo real"
OA--(Visualizar alarmas OA)
UR--(Visualizar alarmas UR)
Operador--(Visualizar alarmas O)
(Visualizar alarmas O)--|>VA
(Visualizar alarmas OA)--|>VA
(Visualizar alarmas UR)--|>VA
Operador--(Ver avisos)
OA--DE
(introducir variables)<..DE : <<include>> 
(Introducir condiciones)<..DE : <<include>>
DE<..GA : <<extend>>
UNR--EX
VisualAct--|>EX
(Introducir operador/es)..>VisualAct : <<extend>>
UNR-right-VA
UNR<|--UR
(Disparar alarmas)--Sistema
OA--(Suministrar datos al sistema)
usecase PO as "Puntuar operadores"
UR--PO
(Seleccionar operador)<.up.PO : <<include>>
OA--(Medir rendimiento de operadores)
(Mostrar mensaje).up.>VA : <<extend>>
@enduml