@startuml Horarios
Class Usuario{
    DNI/NIE
    NombreCompleto
    Telefono
    Sexo
}
Class ListaDeClase{
    NombreEstudiante
    NombreAsignatura
}
Class Horarios{
    NombreAsignatura
    HorasAsignatura
    DiaAsignatura

}
Class Asignatura {
    Nombre
}
Class Alta{
    NombreEstudiante
    AsignaturasCursadas
}


Horarios "1..*"--"1" Usuario
Horarios"1"--"*"Asignatura
Asignatura"1..*"--"1"Usuario
Usuario"1"--"1..*"Alta
Asignatura"1"--"1"ListaDeClase