@startuml Sistema
Class Comprador{
    Agregan Productos
    Consultan Precios
    Finalizan compras
    Consultan ofertas
}
Class Proveedor{
    Consultan Precios
    Consultan ofertas
    Avisan nuevos productos
    Incorporar ofertas
    Avisan fin -> elimina oferta

}
Class Vendedor{
    Consultan Precios
    Consultan ofertas
}
Class Administrador{
}
Class Productos{
    Estado
}
Class Oferta{
}

Class RealizarVenta{
    NombreEstudiante
    AsignaturasCursadas
}
Class ConsultarHistoricoVenta{
    NombreEstudiante
    AsignaturasCursadas
}

Compras<|-up-Comprador : finalizan
Ofertas<|-up-Comprador : consultan
Precios<|-down-Comprador : consultan
Productos "1..*"<--"1" Comprador : agregan
Horarios "1..*"<-left-"1" PersonalPDI : ProponerCambios
Horarios "1..*"<-up-"1" PersonalPAS : Modificar
DarAltaEstudiante "1..*"<--"1" PersonalPAS
DarAltaEstudiante "1..*"<--"1" PersonalPDI