@startuml Sistema

Class Usuario{
    NombreCompleto
    Telefono
    Email
    NumeroCuenta
}

Class Producto{
    ProductoID
}

Class Aviso{
    NuevoProducto
    FinalOferta
}

class Precio {
    ProductoID
    PrecioProducto
}
class Compra{
    ReferenciaCompra
    FechaCompra
    DestinoCompra
}

class Oferta {
    Descuento
    ProductoID
    FechaFinalOferta
}

class Destino{
    DestinoCompra
}

class HistoricoVentas{
    NombreUsuario
    Contrseña
}

Compra "1..*"--"1"Usuario 
Oferta "1..*"--"1"Usuario 
HistoricoVentas "1"-up-"1"Usuario
Producto "1..*"--"1" Usuario 
Aviso"1..*"--"1" Usuario 
Compra "1"--"1"Destino
Producto "1"--"1" Oferta
Producto "1"--"1" Precio
Aviso "1"--"1" Oferta
Aviso "1"--"1" Producto
@enduml