@startuml Actividad0
actor Gestor
actor Usuario
actor Abstracto
(Elaborar listas)--Gestor
(Elaborar estadisticas)--Gestor
usecase EC as "Elaborar calendario 
--
 extension ponts: 
 Organizar jornadas"
 (EC)--Gestor
 (Organizar jornadas)..>(EC) : <<extend>>
 usecase Reg as "Registrarse
 "
 usecase RegG as "Registrarse (vista gestor)
 "
 
 Gestor--|>Abstracto
 Usuario--|>Abstracto
 (Ver listas)--Abstracto
 (Ver calendario)--Abstracto
 (Descargar archivos)--Abstracto
 (Reg)--Usuario
 (RegG)--Gestor
 (Subir archivos)--Gestor
 (Acceder a reports)--Gestor 
(RegG)--|>(Reg)
(Enviar notificaciones)-- Usuario
(Ver notificacines)--Usuario 
@enduml