@startuml Horarios

usecase AltaPDI as "Dar alta estudiantes PDI
--
extension points
Buscar en listas de clase
"
Estudiante-(Consultar horarios)
PersonalPDI--(Proponer cambios en el horario)
PersonalPDI--(AltaPDI)
PersonalPAS--(Modificar horarios)
PersonalPAS--(Dar alta estudiantes)

(AltaPDI)--|>(Dar alta estudiantes)

(Dar alta estudiantes).>(Verificar datos estudiantes): <<include>>
(Buscar en listas de clase)..>(AltaPDI): <<extends>>


PersonalPDI--|>Estudiante
PersonalPAS--|>Estudiante
@enduml